### ISSUE TITLE
VS 2015 cannot compile

### ISSUE THREAD

**Issue by dix75** [paulhoux/Cinder#8]
Hi All!

The vc2015_winrt project didn't compile. 
Errors:
- Error	C2065	'GL_BGRA': undeclared identifier	cinder	d:\Projects\Temp\Cinder\src\cinder\gl\TextureFormatParsers.cpp	283
- Error	C2065	'GL_BGR': undeclared identifier	cinder	d:\Projects\Temp\Cinder\src\cinder\gl\TextureFormatParsers.cpp	289	

p.s.
VS 2013 - ok

**Comment by paulhoux** [comment]
Please report this at the official Cinder repo. This one is my personal fork.
